print("Full Name: Kaden Mason Lee")
print("Prefered pronouns: He / Him")
print("My favorite movie is: Mean girls because its so funny", end = " ")
print("I cant stop laughting at least the first time. ALso All the people are hot.")
print("My favorite food is cake, its more of a desert but BREAKFAST LUNCH AND DINNER SHOULD ALL BE JOY")
